version: '3.3'
services:
    nginx:
        image: nginx:1.25.3-alpine
        ports:
            - 8989:80
        depends_on:
            - php
        volumes:
            - .:/application
            - ./docker/config/default.conf:/etc/nginx/conf.d/default.conf

    php:
        build: ./docker
        volumes:
            - .:/application
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        environment:
            - DB_PORT=3306
            - DB_HOST=db
            - DB_USERNAME=root
            - DB_PASS=secret
            - DB_NAME=app_db

volumes:
    db_data: